// Generated by CoffeeScript 1.7.1
(function() {
  var LiveTime;

  LiveTime = (function() {
    function LiveTime(optiuns) {
      this.$datePiker = $(optiuns.datePiker);
      this.$tableLive = $(optiuns.tableLive);
      this.dataBirthday = optiuns.dataBirthday || '';
      this.initDatePiker();
      this.getStorage();
    }

    LiveTime.prototype.renderTable = function() {
      var count, i, j, table, _i, _j;
      console.log('-------------');
      table = '<table class="table table-bordered">';
      count = this.getCountWeek(this.dataBirthday);
      for (i = _i = 0; _i < 60; i = ++_i) {
        table += '<tr>';
        for (j = _j = 0; _j < 53; j = ++_j) {
          if (j === 0) {
            table += "<td class='year'>" + i + "</td>";
          } else {
            if (count >= 0) {
              table += '<td class="select"></td>';
              count = count - 1;
            } else {
              table += '<td></td>';
            }
          }
        }
        table += '<tr>';
      }
      table += '</table>';
      return this.$tableLive.html(table);
    };

    LiveTime.prototype.initDatePiker = function() {
      this.$datePiker.datepicker({
        startView: 2,
        endDate: new Date(),
        todayHighlight: true
      });
      return this.$datePiker.on('changeDate', (function(_this) {
        return function() {
          _this.dataBirthday = _this.$datePiker.datepicker('getDate');
          _this.setStorage();
          return _this.renderTable();
        };
      })(this));
    };

    LiveTime.prototype.getStorage = function() {
      var time;
      time = +localStorage.getItem('timelive');
      if (time) {
        this.dataBirthday = new Date(time);
        this.$datePiker.datepicker('update', this.dataBirthday);
        return this.renderTable();
      }
    };

    LiveTime.prototype.setStorage = function() {
      return localStorage.setItem('timelive', this.dataBirthday.getTime());
    };

    LiveTime.prototype.getCountWeek = function(date) {
      var offset;
      offset = moment(date).twix(new Date()).count('year') * 0.1774568456;
      return moment(date).twix(new Date()).count('week') - offset;
    };

    return LiveTime;

  })();

  new LiveTime({
    datePiker: '#date',
    tableLive: '#table'
  });

}).call(this);

//# sourceMappingURL=main.map
